[package]
name = "sgnow"
version = "0.1.0"
authors = ["pinnouse <cupofpho@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
vulkano = "0.13"
vulkano-shaders = "0.13"
vulkano-win = "0.13"
winit = "0.19"