[package]
name = "sgnow"
version = "0.1.0"
authors = ["pinnouse <futawong@owo.soy>"]
edition = "2018"

[dependencies]

azul = { git = "https://github.com/maps4print/azul", rev = "a6d58ae4fc8e2657981cc510d9f7fbcdc5af0023" }